### ISSUE TITLE
User can not change donate amount after donate button is clicked

### ISSUE THREAD

**Issue by tmextreme** [technofreaky/woocomerce-quick-donation#39]
Hi,

Here is my site http://taafng.org/.

Steps
1. enter an amount and click donation
2. plugin takes you to the checkout page
3. Lets say internet connection breaks or you can just click any other link
4. if you go back to the home page, change the amount and Click on the donation button, it now calls the checkout page but the amount showing is still the previous amount entered

Regards
Tomi

**Comment by technofreaky** [comment]
@tmextreme 
Hi sorry for the delay. i will tell you a small work flow. if its ok then i will work on it

if user add donation for for project a with amount 20$ and due to some thing i returned to home page or disconnected from with website after adding donation. 

and the same user comes again and adds project a with different amount (A => 10$). and this will replace the amount. if same user ties to add diff project when a project exist it will give an error. is this ok ?

**Comment by technofreaky** [comment]
@tmextreme  as there no reply . i am closing this request
