### ISSUE TITLE
Trash & Restore Issue For Donation Orders

### ISSUE THREAD

**Issue by technofreaky** [technofreaky/woocomerce-quick-donation#43]
From the donations, I can trash some donations in a bulk, but I land on a blank page (but the donations are successfully trashed). Same thing happens when I restore the trashed donations, or when I permanently delete the trashed donations

> Issue Reporter : @ierpe
Issue ID : #40

**Comment by technofreaky** [comment]
@ierpe can you please check the same with the latest version 1.3.6 ?

**Comment by ierpe** [comment]
The problem persists...

I noticed in my Chrome console a 404 problem : 

http://loc-bicewp.org/app/plugins/woocommerce-quick-donation/includes/css/admin-style.css returns a 404 -> I checked and the file isn't there
I don't think the problem comes from here though... I have no other error in Apache or my chrome console...

**Comment by macra** [comment]
I noticed this as well, as mentioned in my feedback to a related issue. I had the same blank page occur even deleting a single donation.

**Comment by technofreaky** [comment]
@ierpe @macra can you both please download the latest source from github and kindly check for the same issue. i have fixed today morning and updated in github :)

**Comment by ierpe** [comment]
Hi, still not working for me after the update...

**Comment by ierpe** [comment]
well... actually now it seem to work, maybe it was some caching issue...?

**Comment by technofreaky** [comment]
@ierpe  may be. but without checking the your setup i can't say its  caching issue. i am happy that it worked for you :)
