### ISSUE TITLE
Latest version will not activate

### ISSUE THREAD

**Issue by Wysgraphics** [technofreaky/woocomerce-quick-donation#62]
Initially the updated plugin crashed the admin area. Once I managed to recover from that I tried to activate it from the plugins dashboard and it gives this error:
```php
Parse error: syntax error, unexpected T_PAAMAYIM_NEKUDOTAYIM in
/home2/..../wp-content/plugins/woocommerce-quick-donation/includes/admin/
class-admin-functions.php on line 137
```

I know you tried to fix this in your latest beta release but it still doesn't seem to be working.

**Comment by technofreaky** [comment]
hi 


can you please download the latest version from github and try

**Comment by Wysgraphics** [comment]
I am using Version 1.3.7.1 BETA. Is there a newer one? I'm new to Github... where do I get it?

**Comment by technofreaky** [comment]
Yes new version is in github

On Sat, Nov 14, 2015 at 5:45 am, Wysgraphics < notifications@github.com [notifications@github.com] > wrote:
I am using Version 1.3.7.1 BETA. Is there a newer one? I'm new to Github...
where do I get it?

—
Reply to this email directly or view it on GitHub
[https://github.com/technofreaky/woocomerce-quick-donation/issues/62#issuecomment-156596047] .[https://github.com/notifications/beacon/ABzAf00haxzLYJy0yahm0MDDVEOi5EEEks5pFnSvgaJpZM4GiOaO.gif]

**Comment by Wysgraphics** [comment]
Downloaded, re-installed, same problem. "Plugin could not be activated because it triggered a fatal error."
Parse error: syntax error, unexpected T_PAAMAYIM_NEKUDOTAYIM in /home2/wysdomgr/public_html/XXXXXX/wp-content/plugins/woocommerce-quick-donation/includes/admin/class-admin-functions.php on line 137

**Comment by technofreaky** [comment]
Hi,

Ok could you please tell which version of php are you using

On Sat, Nov 14, 2015 at 8:22 am, Wysgraphics < notifications@github.com [notifications@github.com] > wrote:
Downloaded, re-installed, same problem. "Plugin could not be activated because
it triggered a fatal error."
Parse error: syntax error, unexpected T_PAAMAYIM_NEKUDOTAYIM in
/home2/wysdomgr/public_html/XXXXXX/wp-content/plugins/woocommerce-quick-donation/includes/admin/class-admin-functions.php
on line 137

—
Reply to this email directly or view it on GitHub
[https://github.com/technofreaky/woocomerce-quick-donation/issues/62#issuecomment-156614399] .[https://github.com/notifications/beacon/ABzAfw2fou1yhsoFRji6MsMmAEOYttAqks5pFpl3gaJpZM4GiOaO.gif]

**Comment by Wysgraphics** [comment]
According to my hosting control panel php 5.4.24 running Linux

**Comment by technofreaky** [comment]
Ho ok

Is there any possibility to check for php5.5

On Sat, Nov 14, 2015 at 8:41 am, Wysgraphics < notifications@github.com [notifications@github.com] > wrote:
According to my hosting control panel php 5.4.24 running Linux

—
Reply to this email directly or view it on GitHub
[https://github.com/technofreaky/woocomerce-quick-donation/issues/62#issuecomment-156616967] .[https://github.com/notifications/beacon/ABzAf_CXnby95BDQw1AuVw_k_PzTtI4Xks5pFp3WgaJpZM4GiOaO.gif]

**Comment by Wysgraphics** [comment]
It seems I have an option to use various forms of php 5.4 or 5.6 Beta. No 5.5. But this is all server settings where I host a few different sites. I'm not a programmer so I don't want to break anything because I don't really know how I can restore things if I do.

**Comment by technofreaky** [comment]
Ok I am sorry.. First let me try to replicate the same with the php version you
said and try to fix this

On Sat, Nov 14, 2015 at 8:52 am, Wysgraphics < notifications@github.com [notifications@github.com] > wrote:
It seems I have an option to use various forms of php 5.4 or 5.6 Beta. No 5.5.
But this is all server settings where I host a few different sites. I'm not a
programmer so I don't want to break anything because I don't really know how I
can restore things if I do.

—
Reply to this email directly or view it on GitHub
[https://github.com/technofreaky/woocomerce-quick-donation/issues/62#issuecomment-156618296] .[https://github.com/notifications/beacon/ABzAfwOmIMkxHr5Zy_Oz9tl324z8MWZyks5pFqBugaJpZM4GiOaO.gif]

**Comment by technofreaky** [comment]
@Wysgraphics if you are avaiable can you please come for support chat ? 
https://www.hipchat.com/gVcsNs3aC

**Comment by technofreaky** [comment]
Hi,

After debuging your site i found the below issue with my plugin :( i am sorry for the issue. which will be fixed in few min and update in github
```php
Notice: ob_flush() [ref.outcontrol]: failed to flush buffer. No buffer to flush. in 
/home2/..../wp-content/plugins/woocommerce-quick-donation/includes/
class-quick-donation-functions.php on line 255
```

```php
Fatal error: Call to undefined function openssl_encrypt() in 
/home2/..../wp-content/plugins/woocommerce-quick-donation/includes/
class-quick-donation-functions.php on line 414
```

**Comment by Wysgraphics** [comment]
Thanks! I think I can work it from here :)
